version: '3.6'
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK_SET=022
    - WEBUI_PORT=15080
    volumes:
    - /volumes/qbittorrent/config:/config
    - /mnt/elements_main/torrent:/downloads
    ports:
    - 6881:6881
    - 6881:6881/udp
    - 15080:15080
    - 1080:1080
    
  sickchill:
    image: ghcr.io/linuxserver/sickchill
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /volumes/sickchill/config.ini:/config/config.ini
      - /var/log/:/config/Logs/
      - /mnt/elements_main/torrent/sickchill:/downloads
      - /mnt/elements_main/torrent/sickchill:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
    
  nas:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: ${TZ}
    networks:
      - default
    ports:
      - 139:139
      - 445:445
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/:/mnt
    command: '-s "Bobs;/mnt;yes;no;no" -u "bob;123456" -w "WORKGROUP" '
