version: '3.9'
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - WEBUI_PORT=15080
    volumes:
    - ./stack/volumes/qbittorrent/config:/config
    - ./stack/volumes/qbittorrent/cache:/app/sickchill/sickchill/gui/slick/cache
    - ./stack/volumes/torrent/downloads:/downloads
    - {$LOG_PATH}/qbittorrent:/config/qBittorrent/logs
    ports:
    - 6881:6881
    - 6881:6881/udp
    - 15080:15080
    - 1080:1080
    restart: unless-stopped

  # sickchill:
  #   image: ghcr.io/linuxserver/sickchill
  #   container_name: sickchill
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - /home/pi/stack/volumes/sickchill/config:/config
  #     - /mnt/elements_main/torrent/sickchill:/downloads
  #     - /mnt/elements_main/torrent/sickchill:/tv
  #     - /var/log/sickchill.log:/logs/sickchill.log
  #   ports:
  #     - 8081:8081
  #   restart: unless-stopped

  # nas:
  #   image: dperson/samba
  #   container_name: samba
  #   environment:
  #     - TZ=${TZ}
  #   networks:
  #     - default
  #   ports:
  #     - 139:139
  #     - 445:445
  #   tmpfs:
  #     - /tmp
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - /mnt/:/mnt
  #   command: '-s "Bobs;/mnt;yes;no;no" -u "bob;123456" -w "WORKGROUP" '
    
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - ./stack/volumes/jellyfin/config:/config
      - ./stack/volumes/torrent/downloads:/data/movies
      - {$LOG_PATH}/jellfin:/log
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    
#   plex:
#     image: lscr.io/linuxserver/plex:latest
#     container_name: plex
# #     network_mode: host
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - VERSION=docker
#       - PLEX_CLAIM= #optional
#     volumes:
#       - /home/pi/stack/volumes/plex/config:/config
#       - /mnt/elements_main/torrent/sickchill:/tv
#       - /mnt/elements_main/torrent/completed:/movies
#     ports:
#       - 32400:32400
#       - 1900:1900/udp
#       - 3005:3005
# #       - 5353:5353/udp
#       - 8324:8324
#       - 32410:32410/udp
#       - 32412:32412/udp
#       - 32413:32413/udp
#       - 32414:32414/udp
#       - 32469:32469
#     restart: unless-stopped
    
networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      
