services:
  dns:
    container_name: unbound_dns
    image: klutchell/unbound:latest
    ports:
      - 5053:53/udp
      - 5053:53/tcp
    environment:
      TZ: $TZ
    volumes:
      - $STACK_PATH/unbound/unbound.conf.d:/etc/unbound/unbound.conf.d
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
     - 8089:80/tcp
     - 53:53/tcp
     - 53:53/udp
     - 67:67/udp
    environment:
     - TZ=$TZ
     - WEBPASSWORD=$PIHOLE_PASSWORD
     - INTERFACE=eth0
     
    volumes:
     - $STACK_PATH/volumes/pihole/etc-pihole:/etc/pihole
     - $STACK_PATH/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
#     - /home/pie/stack/application/config/pihole_custom.list:/etc/pihole/custom.list:ro
     - /var/log/pihole/log:/var/log/pihole.log
     - /var/log/pihole/log:/var/log/pihole/FTL.log
    dns:
     - 127.0.0.1
    cap_add:
     - NET_ADMIN
    restart: unless-stopped
    

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      
