services:

  dns:
    container_name: unbound_dns
    image: klutchell/unbound:latest
    ports:
      - 5053:53/udp
      - 5053:53/tcp
    environment:
      TZ: $TZ
    volumes:
      - $STACK_PATH/unbound/unbound.conf.d:/etc/unbound/unbound.conf.d
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
     - 80:80/tcp
     - 53:53/tcp
     - 53:53/udp
     - 67:67/udp
     - 123:123/udp
     - 443:443/tcp
    environment:
     - TZ=$TZ
     - FTLCONF_dns_interface=eth0
     - FTLCONF_dns_listeningMode=all
     - FTLCONF_dns_upstreams='127.0.0.1#5053'
     #     - FTLCONF_webserver_api_password='admin'
#    volumes:
#      - $STACK_PATH/pihole:/etc/pihole
    depends_on:
      - dns
    cap_add:
     - NET_ADMIN
     - SYS_TIME
    restart: unless-stopped

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      
