services:

  dns:
    container_name: unbound_dns
    image: klutchell/unbound:latest
    ports:
      - 5053:53/udp
      - 5053:53/tcp
    environment:
      TZ: $TZ
    volumes:
      - $STACK_PATH/unbound/unbound.conf.d:/etc/unbound/unbound.conf.d
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8053:80/tcp
    volumes:
      - $STACK_PATH/pihole/etc-pihole:/etc/pihole
      - $STACK_PATH/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /var/log/pihole.log:/var/log/pihole.log
    cap_add:
      - NET_ADMIN
    environment:
      FTLCONF_LOCAL_IPV4: $HOST_IP
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.yourDomain.lan
      VIRTUAL_PORT: 80
      WEBPASSWORD: IOtSt4ckP1Hol3
      INTERFACE: eth0
      TZ: $TZ
    dns:
      - 127.0.0.1
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using nginx-proxy
      - 'yourDomain.lan:192.168.1.250'
#      - 'pihole pihole.yourDomain.lan:192.168.1.250'
#      - 'sickchill sickchill.yourDomain.lan:192.168.1.250'
#      - 'qbitorrent qbitorrent.yourDomain.lan:192.168.1.250'
    restart: always

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      
