version: '3.6'
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=${TZ}
      - SUBFOLDER=/ #optional
    volumes:
      - /home/pie/stack/volume/emulatorjs/config:/config
      - /home/pie/stack/volume/emulatorjs/data:/data
    ports:
      - 3003:3000
      - 80:80
      - 4001:4001 #optional

networks:
  default:
    driver: bridge
    ipam:
      driver: default
#  nextcloud:
#    driver: bridge
#    internal: true
#    ipam:
#      driver: default
