version: '3.8'

services:
      
  ollama-model:
    volumes:
      - /home/pie/stack/volumes/ollama:/root/.ollama
    container_name: ollama-model
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434

  ollama-telegram:
    image: ruecat/ollama-telegram
    container_name: ollama-telegram
    restart: unless-stopped
    depends_on:
      - ollama-model
    environment:
      - TOKEN=6105650473:AAFtQbx81mKl2YV8SxD6K5UCVb1c5JeYBRg
      - OLLAMA_BASE_URL=192.168.1.205

  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: 'http://host.docker.internal:11434'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /home/pie/stack/volumes/open-webui:/app/backend/data
    depends_on:
      - ollama-model
    ports:
      - 8181:8080
    environment:
      - OPENAI_API_BASE_URLS=https://api.openai.com/v1
      - OPENAI_API_KEYS=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
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
