version: '3.9'
services:

  dns:
    container_name: unbound_dns
    image: klutchell/unbound:latest
    ports:
      - 5053:53/udp
      - 5053:53/tcp
    environment:
      - TZ=${TZ}
    volumes:
      - /home/pi/stack/volumes/unbound/unbound.conf.d:/etc/unbound/unbound.conf.d
    restart: unless-stopped

  nginx-proxy:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.yourDomain.lan
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /home/pi/stack/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
    volumes:
      - /home/pi/stack/volumes/pihole/etc-pihole:/etc/pihole
      - /home/pi/stack/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /var/log/pihole.log:/var/log/pihole.log
    cap_add:
      - NET_ADMIN
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.250
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.yourDomain.lan
      VIRTUAL_PORT: 80
      WEBPASSWORD: IOtSt4ckP1Hol3
      INTERFACE: eth0
    dns:
      - 127.0.0.1
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using nginx-proxy
      - 'yourDomain.lan:192.168.1.250'
      - 'pihole pihole.yourDomain.lan:192.168.1.250'
      - 'sickchill sickchill.yourDomain.lan:192.168.1.250'
      - 'qbitorrent qbitorrent.yourDomain.lan:192.168.1.250'
    restart: always



networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      
